# Generated by Django 5.2.2 on 2025-07-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
